### ISSUE TITLE
Cannot call rotate method

### ISSUE THREAD

**Issue by kj-brown** [appium/appium_capybara#19]
Hi,

I've added your gem into my gemfile, but when calling the rotate method in the steps it tells me it's not defined. Am I missing something?

**Comment by bootstraponline** [comment]
There is a rotate method [defined](https://github.com/appium/appium_capybara/blob/6dc2f6767d7781b9db8fd84fb7a7e2b130548faa/lib/appium_capybara/driver/appium/driver.rb#L75). How are you calling it?

**Comment by bootstraponline** [comment]
I checked and rotate works.

```ruby
# code from sample
# https://github.com/appium/appium_capybara/tree/master/example
# start a Pry session and paste the following code
# run from the example folder
require 'appium_capybara'

Capybara.register_driver(:appium) do |app|
  opts = Appium.load_appium_txt file: File.join(Dir.pwd, 'appium.txt')
  Appium::Capybara::Driver.new app, opts
end

Capybara.default_driver = :appium

capy_driver = Capybara.current_session.driver
capy_driver.browser
```

```
[11] pry(main)> capy_driver.rotate :landscape
=> "LANDSCAPE"
[12] pry(main)> capy_driver.rotate :portrait
=> "PORTRAIT"
```

**Comment by kj-brown** [comment]
Thanks - I'm trying to call it whilst using it as part of a cucumber test, but instead I just get 

`undefined method 'rotate' for nil:NilClass`

**Comment by bootstraponline** [comment]
Yes, it's the same as nil.rotate.

```
$ pry
[1] pry(main)> nil.rotate
NoMethodError: undefined method `rotate' for nil:NilClass
```

The issue is in your code, not the appium project.

**Comment by kj-brown** [comment]
Thank you - had to call `capy_driver = Capybara.current_session.driver` in the actual step definition file.

Many thanks!
