### ISSUE TITLE
Unnecessary relaunching of IOS simulator when calling Capybara::Session#reset! in session_ext.rb

### ISSUE THREAD

**Issue by chris1248** [appium/appium_capybara#21]
I'm running a bunch of rspec tests that use capybara to test a web-product.
So I found this library here to target appium. I use appium so I can test our web-product on IOS devices. Either in the IOS simulator, or on a real IOS device.

Anyways, when I run one rspec example, like this:

    example "Dummy test" do
      visit "/author/surveys/#{jedi.id}"
    end

So after the example is done, and my local config(:after) blocks are run, I expect the IOS simulator to be left as is. 
Nope.

After everything is done, a call to reset the sessions occurs. In my case, the IOS simulator is then completely closed, and then relaunches itself again. In other words a completely useless call, since the safari browser is already reset. This takes a freaking long time, and thus my rspec test that takes 3.4 seconds on chrome, takes 34 to 40 seconds on IOS. 

Using Capybara 2.4.4 the call to reset the sessions occurs here:
**../gems/capybara-2.4.4/lib/capybara/rspec.rb**

    config.after do
      if self.class.include?(Capybara::DSL)
        Capybara.reset_sessions!

Which eventually reaches here:
**../gems/appium_capybara-1.2.1/lib/appium_capybara/ext/session_ext.rb**

    module Capybara
      class Session
        def reset!
          # Work around for issue https://github.com/jnicklas/capybara/issues/1237
          browser_initialized = driver.respond_to?(:browser_initialized?) ? driver.browser_initialized? : true
    
          if @touched && browser_initialized
            driver.reset!

Which then goes thru here:
**../gems/appium_capybara-1.2.1/lib/appium_capybara/driver/appium/driver.rb**

    # override
    def reset!
      # invoking the browser method after the browser has closed will cause it to relaunch
      # use @appium_driver to avoid the relaunch.
      @appium_driver.reset if @appium_driver
    end

So I'd like to know how can I prevent the IOS simulator from constantly relaunching between rspec examples? It's slowing down my test runs by about a **1000%**

**Comment by TheMetalCode** [comment]
Based on my experience, this probably has nothing at all to do with appium_capybara, and everything to do with Appium itself.

Assuming you have something like this in your spec_helper.rb:

```ruby
  config.before(:each) do
    $driver.start_driver
  end

  config.after(:each) do
    driver_quit
  end
```

The call to .start_driver necessarily involves a close/relaunch of the iOS simulator. If you wish to run all your tests in a single simulator session, you want to use before(:all) instead so the .start_driver call only happens at the beginning of the test run, and not before every single test.

**Comment by Jonahss** [comment]
Appium relaunches the simulator between sessions, and also cleans it by
default. There are command-line flags for the server which can be passed to
modify this behavior.

Specifically look at no-reset and full-reset

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
​

**Comment by chris1248** [comment]
None of my rspec code directly calls .start_driver. That actually is in the appium_capybara code itself: See /appium_capybara/driver/appium/driver.rb

    # override
    #
    # Creates and starts a new appium driver.
    # To access the browser without creating one use @browser
    def browser
      unless @browser
        @appium_driver = Appium::Driver.new @options
        # browser is the standard selenium driver without any appium methods
        @browser = @appium_driver.start_driver
      end
      @browser
    end

So yes, appium_capybara is directly involved in this mess. In fact it is involved in the second code snippet I posted. 
If want to use the before(:all) construct than I would probably abandon appium_capybara altogether, and directly use ruby appium_lib instead.

**Comment by chris1248** [comment]
bump?

**Comment by bootstraponline** [comment]
You need to set the noReset [desired capability](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md) to true. If you want everything in a single session, then make sure start_driver is only invoked once. Starting the driver again will cause the previous driver to end since a single appium process is unable to handle more than one session. 

I think this is user error and not an appium issue.

**Comment by chris1248** [comment]
My start_driver call was only getting called once. Also previously I had tried the noReset option, and it didn't work. Because I didn't know where to put it. The docs don't exactly state where to put it.
So in frustration, I put **noReset** in three different places, and it worked!

Then by process of elimination I was able to figure out which of the three locations actually affected the resetting behavior.

    # Setup the capabilities
     desired_caps_ios = {
       platform:        "Mac",
       platformName:    "iOS",
       platformVersion: "8.3",
       browserName: "Safari",
       #safariInitialUrl: 'www.instructure.com',
       noReset: true # <-- HERE is what worked!
     }
   
     appium_lib_options = {
       server_url:           url,
       debug: false, # Turn off a deluge of debugging messages
       noReset: true # <-- HERE doesn't do anything
     }
     all_options = {
       browser: :safari,
       appium_lib:  appium_lib_options,
       caps:        desired_caps_ios,
       noReset: true # <-- HERE doesn't do anything either
     }

I'd have to say that the docs for **where** the capabilities need to be set need to be improved.
