### ISSUE TITLE
appium_driver.start_driver times out

### ISSUE THREAD

**Issue by anthonygreen** [appium/appium_capybara#23]
OSX 10.9.5
Emulator running Android 4.3.1
Appium 1.4.6

the following ruby code in irb 

    require 'selenium-webdriver'
    require 'appium_lib'

     desired_caps = {
       caps:  {
            platformName:  'Android',
            platformVersion: '4.3.1',
            deviceName:    'jelly-bean',
            browserName:   'Browser',
        }
    }

    @appium_driver = Appium::Driver.new(desired_caps) 

    @selenium_driver = @appium_driver.start_driver 

time out on the last line

    Selenium::WebDriver::Error::WebDriverError: An operation did not complete before its timeout expired. (Original error: timeout: Adb command timed out after 30 seconds
    (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Mac OS X 10.9.5 x86_64))

tail of the appium console:

      info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data","status":0}
      info: Chromedriver: Set chromedriver binary as: /Users/greena28/Downloads/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
      info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /Users/greena28/Downloads/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
      info: Chromedriver: Successfully cleaned up old chromedrivers
      info: Chromedriver: Spawning chromedriver with: /Users/greena28/Downloads/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515
      info: Chromedriver: [STDOUT] Starting ChromeDriver 2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961) on port 9515
      Only local connections are allowed.
      info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
      info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.9.5"}}}
      info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}
      info: JSONWP Proxy: Got response with status 200: {"sessionId":"3d688fcc95fe243ddc4a6cb7b3db3111","status":21,"value":{"message":"timeout: Adb command timed out after 30 seconds\n  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf...
      info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}
      info: JSONWP Proxy: Got response with status 200: {"sessionId":"eebe17ea9be3c7f28a57619c3da50042","status":21,"value":{"message":"timeout: Adb command timed out after 30 seconds\n  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf...
      info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}

The browser launches in the emulator but that information does not appear to be making it back to the console

**Comment by bootstraponline** [comment]
appium_capybara v1.3.0 has been released. Please comment if this is still an issue on the new version. Make sure you're using at least appium server version 1.5.2.
