### ISSUE TITLE
Appium Capybara not supporting native Capybara web methods

### ISSUE THREAD

**Issue by achyuthgit** [appium/appium_capybara#26]
Hello All,

I have written Capybara script for web and now trying to run same script on mobile using the Appium Capybara lib, it does support most of the methods but still faces issues with below method

` page.first(:link, link_text).click`

I am getting below error after running the scipt

 `undefined method `click' for nil:NilClass (NoMethodError)
`

**Comment by bootstraponline** [comment]
Are you in the web context or native context? With appium, you have to explicitly switch.

**Comment by bootstraponline** [comment]
appium_capybara v1.3.0 has been released. Please comment if this is still an issue on the new version.
