### ISSUE TITLE
Not able to call rotate method

### ISSUE THREAD

**Issue by jeet4320** [appium/appium_capybara#30]
I used below configurations but not able to call rotate method using 
[11] pry(main)> capy_driver.rotate :landscape
[12] pry(main)> capy_driver.rotate :portrait

Error:
Selenium::WebDriver::Error::NoSuchDriverError: A session is either terminated or not started

configurations:
require 'appium_capybara'

capabilities = {
  deviceName: "iPhone 7",
  platformName: "iOS",
  app: ipa_file_path,
  automationName: "XCUITest",
  platformVersion: "10.3.3",
  udid: "*",
  showXcodeLog: "true",
  xcodeOrgId: "*",
  xcodeSigningId: "* Developer",
  autoGrantPermissions: true
}

Capybara.register_driver(:appium) do |app|
  appium_lib_options = {
      server_url:           url
  }
  all_options = {
      appium_lib:  appium_lib_options,
      caps:        capabilities
  }
  @driver_appium = Appium::Capybara::Driver.new app, all_options
end

Capybara.default_driver = :appium

capy_driver = Capybara.current_session.driver

..........

My driver contains look like below:
#<Appium::Driver:0x007fbc79d0fe48
 @appium_debug=true,
 @appium_device=:ios,
 @appium_port=4723,
 @appium_server_status={"build"=>{"version"=>"1.6.5", "revision"=>nil}},
 @appium_wait_interval=0.5,
 @appium_wait_timeout=30,
 @automation_name=:xcuitest,
 @caps=
  #<Selenium::WebDriver::Remote::W3C::Capabilities:0x007fbc79d0fa10
   @capabilities=
    {:deviceName=>"iPhone 7",
     :platformName=>"iOS",
     :app=>"app.ipa",
     :automationName=>"XCUITest",
     :platformVersion=>"10.3.3",
     :udid=>"**",
     :showXcodeLog=>"true",
     :xcodeOrgId=>"***",
     :xcodeSigningId=>"* Developer",
     :autoGrantPermissions=>true,
     :proxy=>nil}>,
 @custom_url="http://localhost:4723/wd/hub",
 @default_wait=0,
 @driver=#<Selenium::WebDriver::Remote::Driver:0x..f795fb501b57dbca browser=:"">,
 @export_session=false,
 @http_client=
  #<Selenium::WebDriver::Remote::Http::Default:0x007fbc785ca300
   @http=#<Net::HTTP localhost:4723 open=false>,
   @open_timeout=999999,
   @proxy=nil,
   @read_timeout=999999,
   @server_url=#<URI::HTTP http://localhost:4723/wd/hub/>>,
 @listener=nil,
 @sauce_access_key=nil,
 @sauce_endpoint="ondemand.saucelabs.com:443/wd/hub",
 @sauce_username=nil>

**Comment by KazuCocoa** [comment]
Could you attach some gem's version? such as `ruby_lib`, Appium server and this library.

**Comment by KazuCocoa** [comment]
The following error can see if sessions are disconnected.

```
Selenium::WebDriver::Error::NoSuchDriverError: A session is either terminated or not started
```

Please add more data especially Appium server-side debug logs.
I'll re-open again then,
