### ISSUE TITLE
Gesture cannot be processed correctly

### ISSUE THREAD

**Issue by NikitaSmall** [appium/appium_capybara#35]
Good day,

We use `appium`, `capybara`, and this gem to test iOS application. The problem is that we can't use gestures (touch action especially) in our tests. We tried to perform it like this:

```ruby
current_driver = Capybara.current_session.driver
Appium::TouchAction.new(current_driver).tap(x: 45, y: 110, duration: 1000).release.perform
```

But we got this error:

```
NoMethodError:
       undefined method `touch_actions' for #<Appium::Capybara::Driver:0x007f8575e1a760>
```

Do you have any other options to fire this action on?

### More details about initialization:
Nothing really specific. We initialize driver like this:

```ruby
# options is a hash of capabilities.
options = {
  caps: {
    platformName: 'ios',
    deviceName: 'iPhone X',
    platformVersion: '11.0',
    automationName: 'XCUITest',
    app: path_to_app
  }
}
Capybara.register_driver(:appium_ios) do |app|
    Appium::Capybara::Driver.new(app, options)
end

Capybara.default_driver = :appium_ios
```

**Comment by KazuCocoa** [comment]
@NikitaSmall
Could you attach the following versions?

- appium_lib
- appium_lib_core

In addition, `XCUITest` haven't support `Appium::TouchAction.new` yet.

- How about using `mobile:` actions? ( You can also call [these shortcut methods](http://www.rubydoc.info/github/appium/ruby_lib/Appium/Ios/Xcuitest/Gesture), though.)
    - https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md

**Comment by genious234** [comment]
I am using capybara and appium driver Appium::TouchAction.new(current_driver) is working fine for uiautomator2 tests.

**Comment by KazuCocoa** [comment]
thanks 👍 
Will close this for now. Please create a new one
