### ISSUE TITLE
Update run time dependency for latest version of capybara

### ISSUE THREAD

**Issue by kannans5** [appium/appium_capybara#36]
Is it possible to add_runtime_dependency for the latest version of capybara?
https://github.com/teamcapybara/capybara/releases

I use capybara and appium_capybara, but I could not bump up my version of capybara to ~> 3.0 since it conflicts with the dependency for appium_capybara.

```
Bundler could not find compatible versions for gem "capybara":
  In Gemfile:
    capybara (~> 3.0.3)

    appium_capybara was resolved to 1.4.1, which depends on
      capybara (~> 2.7)

**Comment by jlipps** [comment]
I'm not really sure what's going on with this repo. @KazuCocoa do you know the best way to resolve this?

**Comment by KazuCocoa** [comment]
I'll take a look at the release note and changes.
If they have no conflicts between 2.x and 3.x, we can easy to update them.

I've seen issues about capybara x Ruby x Appium. (And capybara is one of major automation ways in Ruby world.)
So I'd like to keep this repo as possible. (But it depends on my time, so far)

**Comment by KazuCocoa** [comment]
📝 
https://github.com/KazuCocoa/appium_capybara/tree/apply_capybara_3

**Comment by KazuCocoa** [comment]
@kannans5 
Could you try v1.5.0?
https://github.com/appium/appium_capybara/blob/master/release_notes.md#v150-2018-05-08 

---

I've checked Capybara's release note, read codebase and run examples. I hope it works without breaking something...

**Comment by kannans5** [comment]
I could run my tests with latest version of capybara and appium_capybara v1.5. Thanks for updating the dependency.
