### ISSUE TITLE
[appium_lib, ruby, capybara, site_prism] UIAElements don't have the attribute 'isContentEditable'

### ISSUE THREAD

**Issue by rodrigojmartin** [appium/appium_capybara#4]
Hello!

I'm using ruby 2.1.1, appium_lib 4.1.0, appium_capybara 0.0.2, selenium-webdriver 2.41.0.

With site_prism, I'm defining  page object elements for an IOS Native application, as follows:

element :domain, :xpath, "//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIATextField[1]"
element :first_name, :xpath, "//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIATextField[2]"
element :password, :xpath, "//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIASecureTextField[1]"

When trying to execute the following line:
@mobile_login.domain.set 'mydomain.net'
@mobile_login.first_name.set 'axel'
@mobile_login.password.set 'axel1'

I receive the following error in the console:

UIAElements don't have the attribute 'isContentEditable' (Selenium::WebDriver::Error::UnknownCommandError)
Not implemented in this context, try switching into or out of a web view (Selenium::WebDriver::Error::UnknownError)
/home/rodrigomartin/.rvm/gems/ruby-2.1.1@mobileIOS-automation/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/response.rb:51:in `assert_ok'
/home/rodrigomartin/.rvm/gems/ruby-2.1.1@mobileIOS-automation/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/response.rb:15:in`initialize'
/home/rodrigomartin/.rvm/gems/ruby-2.1.1@mobileIOS-automation/gems/selenium-webdriver-2.41.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'

Any help on this will be really appreciated.
If you need more info, please let me know.

Regards!

**Comment by Gaddale** [comment]
Hi Adids,

I am trying to automate mobile app<Android> using Capybara, Appium and Cucumber. Driver is able to find elements in step definitions but not in page classes. Please help me in suggesting some solutions

Capybara.rb
-------------------------------------------------------------------
require 'capybara/cucumber'
require 'selenium-webdriver'
require 'appium_capybara'


desired_caps = {
        platformName: 'android',
        versionNumber: '6.0.1',
        deviceName: 'Nexus',
        appPackage: 'com.aconex.aconexmobileandroid',
        appActivity: 'view.SplashActivity',
        app: absolute_app_path
}

Capybara.configure do |config|
  config.default_max_wait_time = 180
  config.default_driver = :appium
  Capybara.register_driver(:appium) do |app|
    appium_lib_options = { server_url:  "http://127.0.0.1:4723/wd/hub" }
    all_options = {
        appium_lib:  appium_lib_options,
        caps:        desired_caps
    }
    Appium::Capybara::Driver.new app, all_options
  end
end

env.rb
-------------------------------------------------------------
$LOAD_PATH.unshift(File.dirname(__FILE__) + '/../pages')

APP_PATH = '.apk File Path'

def absolute_app_path
  File.join(File.dirname(__FILE__), APP_PATH)
end

**Comment by bootstraponline** [comment]
> Driver is able to find elements in step definitions but not in page classes.

It works fine in [the sample code](https://github.com/appium/appium_capybara/tree/master/example). I suggest starting from there and then seeing what's different.
