### ISSUE TITLE
Incompatibility with Capybara 3.27

### ISSUE THREAD

**Issue by cyrilchampier** [appium/appium_capybara#51]
See details here:
https://github.com/teamcapybara/capybara/issues/2234

[This extension](https://github.com/appium/appium_capybara/blob/master/lib/appium_capybara/ext/selector_query_ext.rb#L4) breaks the call from [AncestorQuery](https://github.com/teamcapybara/capybara/blob/ba124973cef768b22c634629e5c5b89e89c633e1/lib/capybara/queries/ancestor_query.rb#L11) to [SelectorQuery](https://github.com/teamcapybara/capybara/blob/ba124973cef768b22c634629e5c5b89e89c633e1/lib/capybara/queries/selector_query.rb#L126)

**Comment by KazuCocoa** [comment]
thanks!

**Comment by mnohai-mdsol** [comment]
Curious, has there been any updates to this?

**Comment by KazuCocoa** [comment]
No, from me

**Comment by KazuCocoa** [comment]
Could someone help to check https://github.com/appium/appium_capybara/pull/55 if it is enough for now?
