### ISSUE TITLE
Cant use hide_keyboard on Android native app

### ISSUE THREAD

**Issue by AlonaPF** [appium/appium_capybara#52]
In my test i need to use hide_keyboard method but seems like it does not work with appium capybara. There is an appium method @driver.hide_keyboard so in my case i am using it this way:

`Capybara.current_session.driver.hide_keyboard`

However it gives error 
```
NoMethodError: undefined method 'hide_keyboard' for #<Appium::Capybara::Driver:0x00007fe5ab0914e0>

  0) My Account tests Verify user can be created successfully and then login
     Failure/Error: Capybara.current_session.driver.hide_keyboard

     NoMethodError:
       undefined method `hide_keyboard' for #<Appium::Capybara::Driver:0x00007fe5ab0914e0>
```

Appium logs can be found here:
https://gist.github.com/AlonaPF/8178fc74dbe3cba94de810b98c22f635

**Comment by KazuCocoa** [comment]
Thanks.
Could you share your gem info relevant to this appium_capybara version?
capybara, appium_lib, appium_lib_core

**Comment by AlonaPF** [comment]
Sure @KazuCocoa ,
Here we go:

appium_lib (10.4.1)
appium_capybara (1.9.0)
appium_lib_core (3.2.3)

**Comment by KazuCocoa** [comment]
thanks. WIll take a look

**Comment by KazuCocoa** [comment]
You can call the appium commands via `appium_driver` like `Capybara.current_session.driver.appium_driver.hide_keyboard`.

Methods defined in https://www.rubydoc.info/gems/appium_capybara/1.9.0/Appium/Capybara/Driver can call as `apybara.current_session.driver.xxxx` directly.
(This lib is designed so.)

i.e.: https://github.com/appium/appium_capybara/blob/master/example/spec/ios_example_spec.rb#L13

Will update documentation

**Comment by AlonaPF** [comment]
Thanks alot for your help @KazuCocoa 
Will try that out
