### ISSUE TITLE
Is there a way to add parallel execution on emulators/simulators?

### ISSUE THREAD

**Issue by AlonaPF** [appium/appium_capybara#56]

**Comment by KazuCocoa** [comment]
What about https://github.com/grosser/parallel_tests ?

e.g. 
- https://github.com/appium/ruby_lib/tree/master/ios_tests
- https://github.com/appium/ruby_lib_core#run-parallel-tests-with-parallel_tests-gem


https://appium.io/docs/en/advanced-concepts/parallel-tests/ also helps to which capabilities affect to parallel execution.
https://discuss.appium.io/ also maybe has the topic

**Comment by AlonaPF** [comment]
Thanks @KazuCocoa 
very useful links
