### ISSUE TITLE
Selenium::WebDriver::Error::InvalidElementStateError: Cannot set the element to 'abc'. Did you interact with the correct element?

### ISSUE THREAD

**Issue by vidhijain24** [appium/appium_capybara#57]
I am using rspec framework for mobile automation testing. There I use appium_capybara along with appium_lib.

When I am trying to set any value in the text box, it throws an exception:
**Selenium::WebDriver::Error::InvalidElementStateError: Cannot set the element to 'abc'. Did you interact with the correct element?**

My code is:
`$capy_driver = Capybara.current_session.driver`
`$capy_driver.find_custom(:xpath, "//android.widget.ImageView[@text='Email Address']")[0].send_keys 'abc'`

Here click is working, but when I use send key then it throws exception.

Thanks
Vidhi

**Comment by mykola-mokhnach** [comment]
I don't think `ImageView` is capable to accept a user input

**Comment by vidhijain24** [comment]
@mykola-mokhnach, This is what I does not understand how to handle this? 
![app](https://user-images.githubusercontent.com/60422141/84537514-8a053a80-ad0d-11ea-82e8-d777cd1d5c64.png)

**Comment by KazuCocoa** [comment]
What the page source?

**Comment by vidhijain24** [comment]
this is what u want?
![page-source](https://user-images.githubusercontent.com/60422141/84632055-fd749b00-af0b-11ea-9005-2fd32649311a.jpg)

**Comment by KazuCocoa** [comment]
Thanks. As Android, the element seems an image. So, Appium could not type texts via Android framework, I guess.

If you can fill some strings in the area via adb command such as `$ adb shell input text xxxx` mobile:type or typing texts via mobile:shell may help.
https://appium.io/docs/en/commands/mobile-command/

**Comment by KazuCocoa** [comment]
Close since this is not Appium side issue.

If you can switch the element with EditTest, for example, I think sendKeys will work for it.
